### ISSUE TITLE
The final archive from tempdir is not being returned correctly

### ISSUE THREAD

**Issue by bbdev2** [ngandrass/moodle-quiz_archiver#10] opened 2024-01-10 09:13 UTC
Moodle: 4.1.18 (from https://download.moodle.org/windows/)
DB: MariaDB 10.4.28
OS: Windows 11

When moodle cron task is launched in Flask web-server messages I see this:
[2024-01-10 11:39:25,513] | INFO     | moodle-quiz-archive-worker | Enqueued job c29c4636-af93-11ee-9041-a85241f26fd0 from 127.0.0.1
[2024-01-10 11:39:25,514] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Processing job c29c4636-af93-11ee-9041-a85241f26fd0
[2024-01-10 11:39:29,288] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Generated "attempt-54-student01_2024-01-10-11-39-26"
[2024-01-10 11:39:32,611] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Generated "attempt-58-student01_2024-01-10-11-39-30"
[2024-01-10 11:39:35,775] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Generated "attempt-59-student01_2024-01-10-11-39-33"
[2024-01-10 11:39:38,883] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Generated "attempt-55-student02_2024-01-10-11-39-36"
[2024-01-10 11:39:38,972] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Wrote metadata for 4 quiz attempts to CSV file
[2024-01-10 11:39:39,006] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Backup ede7296ec78b0ab29e2eb87186d158b7 not finished yet. Waiting 30 seconds before retrying ...
[2024-01-10 11:40:09,041] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Backup ede7296ec78b0ab29e2eb87186d158b7 not finished yet. Waiting 30 seconds before retrying ...
[2024-01-10 11:40:39,088] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Backup ede7296ec78b0ab29e2eb87186d158b7 not finished yet. Waiting 30 seconds before retrying ...
[2024-01-10 11:41:09,119] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Backup ede7296ec78b0ab29e2eb87186d158b7 not finished yet. Waiting 30 seconds before retrying ...
[2024-01-10 11:41:39,341] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Downloaded 47721852 bytes to C:\Users\AntNest\AppData\Local\Temp\tmpn_pojv_j/quiz_archiver-activity-backup-38-20240110-113925.mbz
[2024-01-10 11:41:39,344] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Downloaded 47721852 bytes of backup ede7296ec78b0ab29e2eb87186d158b7 to C:\Users\AntNest\AppData\Local\Temp\tmpn_pojv_j/quiz_archiver-activity-backup-38-20240110-113925.mbz
[2024-01-10 11:41:39,345] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Calculating file hashes ...
[2024-01-10 11:41:39,522] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Generating final archive ...
[2024-01-10 11:41:41,698] | INFO     | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Uploading artifact "C:\Users\AntNest\AppData\Local\Temp\tmp5yoftp6m/quiz-archive-2021 Final, 5-6-8_2024-01-10-11-39-25.tar.gz" (size: 48882751 bytes) (sha256sum: 4a10444e2d92f91018345ce4c7162a66c86f566fb7e9941f9f2507aab875febb) to "http://localhost/webservice/upload.php"
[2024-01-10 11:41:41,851] | ERROR    | quiz_archive_job::<c29c4636-af93-11ee-9041-a85241f26fd0> | Job failed with error: Moodle webservice upload returned error "missingparam". Message:
Error code: missingparam

**Comment by ngandrass** [comment] 2024-01-10 09:52
Which versions of the Moodle plugin and worker service are you using? Issue #11 could also be related to your setup. I never tested this things on Windows.

Your log message indicates that you are *not using Docker* but run the service worker directly on the same host OS your webserver runs on. Is this correct?

**Comment by bbdev2** [comment] 2024-01-10 13:03
yes, it's correct. I used manual deployment without the docker container. Moodle plugin version: 2024010500. Worker version: 1.3.0

**Comment by ngandrass** [comment] 2024-01-12 17:39
Please try again with version [v1.2.3](https://github.com/ngandrass/moodle-quiz_archiver/releases/tag/v1.2.3)

**Comment by bbdev2** [comment] 2024-02-02 09:18
I'll return to your project in 2-3 months. I can't check changes now. There are many other tasks.

**Comment by ngandrass** [comment] 2024-02-07 10:17
Sorry, I was unable to reproduce this. I'll close this issue for now, but feel free to re-open it or submit another issue once you find time to get back to this project :)

**Closed by ngandrass** 2024-02-07 10:17 UTC
Labels: can't reproduce
