### ISSUE TITLE
[Bug]: archive job terminated after 30 min when the job_timeout_min is set to 120 min

### ISSUE THREAD

**Issue by ndunand** [ngandrass/moodle-quiz_archiver#23] opened 2024-07-03 14:48 UTC
### Quiz archiver moodle plugin version

latest

### Quiz archiver worker version

latest

### Worker service deployment method

Docker compose

### Moodle Version

Moodle 4.2.8

### PHP Version

PHP 8.1

### Database

MariaDB

### Operating system

Debian 12

### What happened?

Expected behavior: job would terminate only after having been running for 120 min

Actual behavior: job terminates after 30 min

Additional information:
[2024-07-03 14:31:49,034] | WARNING  | archiveworker.quiz_archive_job::<c98c4000-3944-11ef-863f-0242ac120002> | Job termination requested. Terminated gracefully.

### Steps to reproduce

1. Navigate to the archiver page of a quiz
2. Click Archive with default settings
3. Find the above described error

### Relevant quiz archive worker service log output (if applicable)

```text
[2024-07-03 14:31:49,034] | WARNING  | archiveworker.quiz_archive_job::<c98c4000-3944-11ef-863f-0242ac120002> | Job termination requested. Terminated gracefully.
[2024-07-03 14:31:49,110] | INFO     | archiveworker.moodle_quiz_archive_worker | Job c98c4000-3944-11ef-863f-0242ac120002 terminated gracefully
```

**Comment by ndunand** [comment] 2024-07-03 15:25
Sorry, just noted this comes from the Docker environment configuration:
```
      - QUIZ_ARCHIVER_REQUEST_TIMEOUT_SEC=1800
```
closing this issue.

**Comment by ngandrass** [comment] 2024-07-04 12:06
Yes, we have timeouts on both sides. We have a timeout within the

1. Moodle plugin in order to mark jobs as failed and clean up temporary data if the archive worker died, was restarted in between, whatever else might happen ... If we do not handle timeouts at the Moodle side, webservice access tokens that are issued to allow access to quiz results could remain valid for an infinite amount of time. And we do not want webservice tokens that allow such access to remain active for longer than required.
2. archive worker to prevent DDOS attack where an incoming API request can freely choose an arbitrary timeout, keeping the worker busy for a long or nearly infinite amount of time.

If one has set two different values for the timeouts, the smallest timeout will always be used. Or in other words: You can never queue an archive job with a timeout that is longer than the hard timeout configured in the archive worker.

Therefore, this is **not a bug** in particular. However, I checked the **default values** for both settings and found them to be **very inappropriate**. The Moodle plugin defaults to a timeout of 120 minutes while the archive worker kills any job after 30 minutes by default.

I'll adjust both values to a more sensible default of 60 minutes and add a hint to the help text at the plugin settings page that mentions that there also is another timeout in the worker service!

Therefore: Thanks for bringing up this issue nonetheless :+1:

**Comment by ndunand** [comment] 2024-07-04 12:19
Thanks for explaining the rationale behind the two different timeout settings.

Indeed the default values should be equal. It's also a good idea to hint to the user that adjusting one setting requires the other setting to be adjusted – I suppose many people will read the docs too fast (like me).. Thanks for taking this into consideration.

**Comment by ngandrass** [comment] 2024-07-04 12:41
> Indeed the default values should be equal.

Pushed this to the develop branches of both components. Will be part of the next release.

> I suppose many people will read the docs too fast (like me).. 

Or maybe the docs are just way too bloated if people overlook such information ;) I included it in the "Know Pitfalls" section of the README. This way, people hopefully at least find it when they search for "timeout" :+1:

**Closed by ngandrass** 2024-07-04 12:41 UTC
Labels: documentation, enhancement
