### ISSUE TITLE
job_preset_archive_retention_time doesn't seem to work

### ISSUE THREAD

**Issue by martinoesterreicher** [ngandrass/moodle-quiz_archiver#8] opened 2024-01-08 05:38 UTC
The task \quiz_archiver\task\autodelete_job_artifacts is running every hour.
Setting "job_preset_archive_retention_time" is set to 1 day and is locked.

A teacher could set a different time, although its locked in the settings.
I created an archive on friday and its still here after the weekend and wasnt being autodeleted. 

Am I doing something wrong?

**Comment by ngandrass** [comment] 2024-01-08 10:53
Thanks for reporting!

> A teacher could set a different time, although its locked in the settings.

The unlockable retention time preset is fixed with commit f678200d8e231f041d3076fdd25dd5be20727c8b, which will be part of the next release :tada: 

> I created an archive on friday and its still here after the weekend and wasnt being autodeleted.

I could not reproduce problem that artifacts are not being deleted even though the cronjob/task is executed. Just to make sure: You have created an quiz archive with a retention time set to **1 day, not changing the value in the job creation form** and the artifact file was not deleted properly after 1 day?

Please open the details modal for the affected job an check the `Deletion` property:
![image](https://github.com/ngandrass/moodle-quiz_archiver/assets/326180/144d3332-836e-405e-aa2c-83bf802bd617)

![image](https://github.com/ngandrass/moodle-quiz_archiver/assets/326180/fb6b50e4-54a0-4a8d-9d8b-400342310768)

Thanks!

**Comment by ngandrass** [comment] 2024-01-08 10:56
Quick addition since it is not directly obvious:

> Only the archived user data (attempt PDFs, attachments, ...) is deleted, while the job metadata is kept until manually deleted. This procedure allows to document the deletion of archive data in a traceable manner, while the privacy relevant user data is deleted.

Jobs with deleted archives show as:

![image](https://github.com/ngandrass/moodle-quiz_archiver/assets/326180/ce240d65-8011-4cd6-8faa-3a64041bb407)

**Comment by martinoesterreicher** [comment] 2024-01-08 11:03
The unlockable retention time preset is fixed with commit https://github.com/ngandrass/moodle-quiz_archiver/commit/f678200d8e231f041d3076fdd25dd5be20727c8b, which will be part of the next release 🎉
> awesome 

And thanks for clarifying. 
Automatic deletion should be enabled for the archive job I created. But when I check its telling me that Deletion is disabled. 
Quiz Archiver settings look like: 
![quiz archiver settings](https://github.com/ngandrass/moodle-quiz_archiver/assets/31028100/bf4a0ab6-b588-46df-b38c-e2615399ed0f)

while the settings for the archive job looks like: 
![settings for archive job](https://github.com/ngandrass/moodle-quiz_archiver/assets/31028100/ac8f8a66-3014-448a-a907-c850faf5317c)

and the archive information looks like: 
![archive information](https://github.com/ngandrass/moodle-quiz_archiver/assets/31028100/bbbff883-3a8a-4530-b4e5-50fc49e5bd4e)

I will wait for the new update and test again. :)

**Comment by ngandrass** [comment] 2024-01-08 11:09
Thanks for your quick reply!

> I will wait for the new update and test again. :)

And I was thinking to wait with the release so that it could include fixes for the lock-error as well as the archives not being deleted ;)

> Automatic deletion should be enabled for the archive job I created. But when I check its telling me that Deletion is disabled.

Your settings look fine to me. But, I got an idea ... let me check something quickly.

**Comment by ngandrass** [comment] 2024-01-08 11:18
Found it! Turns out that the Moodle Forms API behaves a little unexpected when using the disabled properties. I could quickly patch it for this one field, but would like to create a proper fix for this whole type of problems to prevent future issues.

Long story short: There should be a new release that addresses all these issues today. I'll let you know here once it's out :)

**Comment by martinoesterreicher** [comment] 2024-01-08 11:19
Awesome thanks. :)

**Comment by ngandrass** [comment] 2024-01-08 12:00
Version 1.2.2 just released, incorporating the fixes :tada: 

GitHub: https://github.com/ngandrass/moodle-quiz_archiver/releases/tag/v1.2.2
Moodle Plugin Directory: https://moodle.org/plugins/quiz_archiver/1.2.2/30827

I'll close this issue for now but feel free to re-open it, if you encounter further problems with archive deletion.

---

P.S.: You can set a short duration for archive deletion while also overriding the cronjob / task schedule within the Moodle Admin UI. This allows you to test archive deletion a lot faster ;)

**Closed by ngandrass** 2024-01-08 12:00 UTC
Labels: bug
