### ISSUE TITLE
[Bug]: in the archive setup form, the forbiddenchars and variables do not display correctly in Moodle 4.2

### ISSUE THREAD

**Issue by ndunand** [ngandrass/moodle-quiz_archiver#24] opened 2024-07-04 12:40 UTC
### Quiz archiver moodle plugin version

latest

### Quiz archiver worker version

latest

### Worker service deployment method

Docker compose

### Moodle Version

4.2.8

### PHP Version

PHP 8.1

### Database

MariaDB

### Operating system

Debian 12

### What happened?

Expected behavior:
<img width="691" alt="Screenshot 2024-07-04 at 14 38 08" src="https://github.com/ngandrass/moodle-quiz_archiver/assets/762972/fdc7b35c-66ef-4d62-8b78-28ae3f26c442">
works fine in Moodle 4.4

Actual behavior:
<img width="685" alt="Screenshot 2024-07-04 at 14 37 43" src="https://github.com/ngandrass/moodle-quiz_archiver/assets/762972/b0323997-89a0-47ab-bb11-c394487a7b33">
localized strings are not resolved in Moodle 4.2

Additional information:

### Steps to reproduce

1. Navigate to the archiver page
2. Display the Advanced settings section
3. Click on the Archive name setting tooltip or on the Report name setting tooltip

**Comment by ngandrass** [comment] 2024-07-08 10:11
I was able to reproduce the problem and will look into it now.

**Comment by ngandrass** [comment] 2024-07-08 10:40
Found the problem. Support for variable substitution in language strings of help buttons came with Moodle 4.3. See: https://github.com/moodle/moodle/commit/36b865b3d90f1a0561b01c88b0be59d662a8598d

Since the content for these help buttons comes exclusively from the language strings it will be hard to inject something there. The only quick solution I see would be to have a static language string for Moodle <= 4.2. That's dirty but should at least work.

**Comment by ngandrass** [comment] 2024-07-08 11:07
Fixed with fd86130fbdaaa61b5607ac5dfd7e9944356beea6
Release will follow today

**Closed by ngandrass** 2024-07-08 11:07 UTC
Labels: bug
